### PR TITLE
Add BWSip documentation and link on README

### PR DESCRIPTION
**Pull request by isouza-daitan**
Add BWSip documentation and link them on the README file.

### CODE REVIEW

**Comment by nguyer** [comment]
This is great! Thanks!

**Comment by sledgeRW** [comment]
Can someone please remove me from github communication ... Thanks.

Sledge

**Comment by nguyer** [comment]
Sledge, I don't know that there's any way for us to turn off your notifications. It's pretty easy to manage your notifications in GitHub. Just go to https://github.com/settings/notifications. The other option is that we could take you completely out of the bandwidthcom organization on GitHub. Let me know if you want help turning off the notifications. I'd be happy to help.

**Comment by sledgeRW** [comment]
Hey Nicko,

I never use GitHub...you can just take me off the organization of
GitHub...won't affect anything else...thanks!

sledge



On Thu, Jun 11, 2015 at 3:47 PM, Nicko Guyer <notifications@github.com>
wrote:

> Sledge, I don't know that there's any way for us to turn off your
> notifications. It's pretty easy to manage your notifications in GitHub.
> Just go to https://github.com/settings/notifications. The other option is
> that we could take you completely out of the bandwidthcom organization on
> GitHub. Let me know if you want help turning off the notifications. I'd be
> happy to help.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bandwidthcom/catapult-reference-app-voice-android/pull/2#issuecomment-111257260>
> .
>



-- 


Chad Sattler

Mayor

Bandwidth <http://www.bandwidth.com/>

o 919.260.8117

e csattler@bandwidth.com

**Pull request merged**
